### ISSUE TITLE
无法获取car列表，请问有这个文件么

### ISSUE THREAD

**Issue by Matear890** [kazeik/licheng#1]
http://www.xyangb.cn/licheng/index.php/api/public/getoilprice/

**Comment by kazeik** [comment]
@EnvisDeng 这个文件放在服务端了。你可以看licheng-server的Application/Data目录下。
目前这个项目没有维护了。

**Comment by Matear890** [comment]
谢谢 已经找到

**Comment by Matear890** [comment]
获取今日油价报错了，我通过  licheng-server 未找到接口 
错误信息： http://www.xyangb.cn/licheng/index.php/api/public/getoilprice/?date=2019-09-20 404 (Not Found)
